version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "${neo4j_user}/${neo4j_password}"
      NEO4JLABS_PLUGINS: '["apoc"]'  # Added APOC plugin

    volumes:
      - neo4j_data:/data



  fastapi:
    build: .
    container_name: fastapi_container_approach_2
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - neo4j_user=${neo4j_user}
      - neo4j_password=${neo4j_password}
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
